### ISSUE TITLE
Why having two separate nuget packages (SimpleBrowser  and SimpleBrowser.Webdriver)

### ISSUE THREAD

**Issue by AndersBillLinden** [SimpleBrowserDotNet/SimpleBrowser.WebDriver#28]
Why are SimpleBrowser and SimpleBrowser.Webdriver two separate projects?

**Comment by kevingy** [comment]
I realize this is an old thread, but in the interest of closing old issues...

>Why are SimpleBrowser and SimpleBrowser.Webdriver two separate projects?

The better question is why do they need to be combined?

> I found a logical reason to have the projects merged as one project when I was modifying SimpleBrowser to disallow file urls in a non file url document and found out that it would be the easiest to create a test for the change in SimpleBrowser.WebDriver.

Let me repeat what you just said, a different way, just to see if I understand you. You are suggesting that we combine the two SimpleBrowser products into one just so that a feature modified in SimpleBrowser can be more easily tested using SimpleBrowser.WebDriver. That's the equivalent of saying let's combine Microsoft Word and Microsoft PowerPoint, because I modified the way spell checking works in Word, but it's easier to test in PowerPoint. That's ridiculous.

As is typical, the easiest solution isn't the best solution.

**Comment by Teun** [comment]
Also, I don't really see how it is easier. If you install the package SimpleBrowser.WebDriver, it will also install the version of SimpleBrowser it depends on. If your test is testing something in SimpleBrowser, the test should live there.

**Comment by AndersBillLinden** [comment]
As I remember it, the two projects does not make sense without each other. Anyone developing in one of the repos would be sure to have checked out the other as well (that fact alone is a signal that maybe they should be combined). The repos are not huge, there is no code mass. There is no relief splitting them in two. A motivator to split a repo in two must be some other logical reason. A reason I am asking about in this issue. The easiest solution should always be considered.

**Comment by kevingy** [comment]
>Anyone developing in one of the repos would be sure to have checked out the other as well

This is a false statement. I have used SimpleBrowser for years. I have never used SimpleBrowser.Webdriver.

> There is no relief splitting them in two.

No one has split them into two. SimpleBrowser and SimpleBrowser.WebDriver started as two separate and independent projects. It's actually more work to combine them. That effort that is better spent working on real problems.

If you look at the top three browsers - Chrome, Internet Explorer, and Firefox, all of them work exactly the way SimpleBrowser works. The browser is separate from the browser's corresponding WebDriver. It doesn't make sense for SimpleBrowser to deviate.

I think between Teun and myself, there's enough consensus to close this issue. Thank you for your suggestion, but this will not be implemented.
